// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xghrrqsiykzceeiejtpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnaHJycXNpeWt6Y2VlaWVqdHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTQ3MDQsImV4cCI6MjA1ODY5MDcwNH0.FdyArDapcUlmkqUr5JrqH4Se3h2FSbf0nMcmN8q9xKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);